#!/bin/sh

set -e

# don't do anything when called with other argument than configure
case "$1" in
  configure)
  ;;
  abort-upgrade|abort-remove|abort-deconfigure)
    exit 0
  ;;
  *)
    echo "postinst called with unknown argument \$1'" >&2
    exit 1
  ;;
esac

. /usr/share/debconf/confmodule

# enable required modules
a2enmod ssl perl

# enable optional modules
a2enmod dump_io || echo "Missing some optional Apache module(s), ignoring."

# disable debian's default Apache site
a2dissite default

exit 0
